### ISSUE TITLE
4.3. Split app and vendors - adding vendors

### ISSUE THREAD

**Issue by akatreyt** [survivejs/webpack#17]
In the sample you have 

vendors: ['react']

but no where in that sample page do you define react. On your site you define it as 

config.addVendor('react', bower_dir + '/react/react.min.js');

so I expect it to be the same, if so also need to add the addVendor method.

**Comment by christianalfoni** [comment]
Hi @akatreyt , sorry for late reply, I have been sick with the flue. But up and running again now :-)

Thanks for asking this question, I will update with more information!

The reason is the webpack runs in Node and `['react']` basically means: `require('react')`. So the node module react is loaded. Does that make sense?

**Comment by bebraw** [comment]
@akatreyt Did you manage to resolve this?

**Comment by bebraw** [comment]
There's a [chapter about splitting bundles](http://survivejs.com/webpack/building-with-webpack/splitting-bundles/) now. Closing.
