### ISSUE TITLE
I have translate this repo to chinese version,but how can PR for a new branch named zh-cn

### ISSUE THREAD

**Issue by fakefish** [survivejs/webpack#33]
https://github.com/fakefish/react-webpack-cookbook
this is my forked repo.

**Comment by bebraw** [comment]
I guess the problem is that pull requests are meant to work against an existing branch. I don't think they work with entire branches unless we create a branch for you to PR against.

That said perhaps maintenance-wise it's best to keep the translation at your repository? We can definitely link to it from the main content. In fact there's a link to it right now. Thanks for your great work!

@christianalfoni Any thoughts on this?

**Comment by bebraw** [comment]
The book has changed too much. I'm still interested in translation, though, so feel free to ping me through email if you are interested (paid work). :+1:
