### ISSUE TITLE
Typo/bug in "Advanced Techniques--Configuring React"

### ISSUE THREAD

**Issue by abustamam** [survivejs/webpack#92]
I'm really liking the separation between Webpack and React! I feel like I'm finally understanding Webpack and its various configuration methods. 

I ran into a tiny bug in the Advanced Techniques chapter though. 

https://github.com/survivejs/webpack/blame/b57e8e4f5fe9b1e8ebf7ed5582f953e4d77a38bf/manuscript/advanced_techniques/05_configuring_react.md#L143

This line did not work:

```
process.env.BABEL_ENV = TARGET;
```

I think this was based on an older version of the book, where `TARGET` was equal to `process.env.npm_lifecycle_event`. 

So I just dug up the older copy of the book and it worked fine. 

```
const TARGET = process.env.npm_lifecycle_event
process.env.BABEL_ENV = TARGET
```

I also changed the switch case:

```
switch (TARGET) {
/* ... */
}
```

Less important, there are some weird lines that actually ended up making it to the book:

```
leanpub-start-insert
leanpub-end-insert
```

I don't see that syntax anywhere else, but I might be missing something.

**Comment by bebraw** [comment]
I added the line there so that the chapter works better standalone. I think the Babel section has to grow into a chapter of its own eventually.

Those `leanpub-start-insert` and `leanpub-end-insert` lines are Leanpub specific formatting. The site actually parses those. [Example](http://survivejs.com/webpack/advanced-techniques/configuring-react/). The problem is that GitHub doesn't support the syntax.

Thanks!

**Comment by abustamam** [comment]
Oh I see. Thanks for clarifying so quickly!
